### ISSUE TITLE
Location and Dates

### ISSUE THREAD

**Issue by dasaderi** [OpenCon-Cascadia/planning_in_the_open#1]
The tentative dates for OpenCon Cascadia are **January 11 and 12**. The conference will begin with an evening networking reception on Friday, January 11; talks and workshops will take place on the 12th. As a free conference we are looking to find a organization that will provide a venue and AV equipment at no cost.  

Below are some details about specific space and AV needs.  

No. of Expected Attendees:  120

Room Needs:

- 1 auditorium that can accommodate all attendees and panel-like presentations.
- 3-4 break-out rooms for workshops and hackathons.
- Space that can accommodate a reception with food and drink

AV:
- Microphones for auditorium panel discussions
- Projection capabilities in the auditorium and break-out rooms.

**Comment by dasaderi** [comment]
Ideas for locations and action items decided at last call on June 29, 2018:
- CLSB (OHSU/PSU): Free February 1st and 2nd (Robin)
- White Stag (UO):  Jonathan Cain will check into dates and cost
- Gates Foundation (Seattle): Daniela will ask Ashley Fairly
- Reed: David Isaac will look into Reed as possibility in the winter time
- Portland State Business Accelerator (accelerator@pdx.edu)

The group will report back by July 13, 2018.

**Comment by walecain** [comment]
I have contacted the Event Manager at UO Portland about the Whitestag.  Unfortunately, its not free but, I was able to get an idea of cost.  The basics
- Room 142/144(Auditorium) + Light COurt Commons(Reception & Reservation) $300.00 (for 4 hrs.) + $75.00 per hour (for everything over the 4 hrs.)
- Classrooms (breakout rooms) $160.00 (4 hrs.) + $40.00 ( additional hrs.)
- Weekend fees $120.00 + $30.00 (set up/ take down/ basic tech support)
- No additional tech fees for  basic support and equipment (e.g. Room 142/144 and classrooms have the basic screen, projectors, and audio equipment )
Also,  please see some attached information on Room Rental fees, Additional Fees and a photo of 142/144 in use.
- [UO Portland Room Rental Fees - 051118.pdf](https://github.com/OpenCon-Cascadia/planning_in_the_open/files/2157039/UO.Portland.Room.Rental.Fees.-.051118.pdf)
- [UO Portland Additional Fees - WEB ONLY - 062317.pdf](https://github.com/OpenCon-Cascadia/planning_in_the_open/files/2157040/UO.Portland.Additional.Fees.-.WEB.ONLY.-.062317.pdf)
![rounds with guests](https://user-images.githubusercontent.com/1145136/42189706-66ca599a-7e0e-11e8-99dd-f614dc9e7c94.JPG)

**Comment by dconner3** [comment]
Requested a quote from Reed's Conference and Events Planning. The earliest I will hear back is 7/10/18.

**Comment by dconner3** [comment]
Holding the event at Reed would not be free. [Here is a webpage listing the prices.]( http://reedevents.reed.edu/plan-an-event/facility-use-rates.html) 

OpenCon could be at either the non-profit or (the less expensive) co-sponsor rate. I cannot guarantee that Reed would agree to co-sponsor the event at this time, so it is more prudent to plan at the non-profit rate. 

The most affordable option with the least traveling between buildings would be to hold the event in the Psychology building. Unfortunately, there are no half-day rates.

Location | Cost | Notes
-------- | ---- | -----	
Lecture Hall | $365 | All day on Jan 12
4 break out classrooms | $480 | All day on Jan 12
Reception space | $145 | All day on Jan 11 (no half day rate). I'm not sure if we would need to use campus catering services.
Wifi fees | $250 | $125/day
Guest-service fee | $480 | $4/person. I think this is a one time cost and not per day.
AV fee | $720 | $45/hour at 8 hours (so two AV staff on Jan 12)

All rooms come with projectors and screens, but I am not sure about audio equipment in the classrooms.

Total cost estimate (not including catering or additional AV equipment) around **$2440**.

**Comment by dasaderi** [comment]
@walecain and @dconner3, thank you so much for looking these up. It looks like UO would be cheaper, but still not ideal if we want to have this event free to participants. 

It looks like it might be worth to wait until February and have the CLSB for free. @rchampieux and @daniellecrobinson, other ideas?

**Comment by dconner3** [comment]
I think it is worth considering postponing until February to use the free CLSB site. Their will inevitably be other costs that fundraising will have to cover (speaker travel, food, etc) so having space be free would go a long way toward reducing overall costs. Should we bring this idea back to the larger group?

**Comment by walecain** [comment]
Ditto.

**Comment by daniellecrobinson** [comment]
@dasaderi sounds good to me - @rchampieux what do you think?

**Comment by rchampieux** [comment]
Hi @dasaderi @walecain @dconner3 @daniellecrobinson my apologies for the silence - I'm catching up from my trip.  By this location do you mean the CLSB in February?  If so, I agree and can work with events at OHSU to book it.  We will have a small AV budget to cover that it's very reasonable.  Likely less than $700.

**Comment by dasaderi** [comment]
@rchampieux, yes, sorry, I meant CLSB in February. I think we should just go for it so we can start planning everything else. Also it's a great location and it's affordable. I'd go ahead and book it. Thank you!

**Comment by dconner3** [comment]
Agreed!

**Comment by dasaderi** [comment]
Dates CONFIRMED for February 1-2. The only caveat is that the room at the CLSB on the 1st will be available only after 5pm. @rchampieux will work with OHSU facilities to obtain more details and book the room.

**Comment by dasaderi** [comment]
@daniellecrobinson will check with Mozilla if we can do the Meet and Greet on Friday February 1st at their newly renovated office. Another idea is to do it at Reed. @dconner3 would that cost us money?

**Comment by dconner3** [comment]
Yes, to do just the reception at Reed would still cost money. I am not sure of space availability for the February dates, but the cost of the space would range somewhere between $200-$1200 depending on the size and niceness of the venue. Catering chargers would be extra. Should I look into this or does the renovated Mozilla seem more promising?

**Comment by dasaderi** [comment]
@dconner3, that sounds like too much money for a meet & greet. @daniellecrobinson, do you want to check if Mozilla downtown office space would be available?

**Comment by dasaderi** [comment]
@rchampieux is the room in CLSB confirmed for February 1-2?

**Comment by ashleyfarley** [comment]
Quick logistical question: I know the aimed number is 120. Is this our cap? It might be good to have a cap for communications/marketing.

**Comment by dasaderi** [comment]
Good point about the communication. I think we said that would be our cap, yes. Should we do first register first served? Or should we have reserved positions for students/postdocs, PIs, librarians, etc. to ensure a balanced and diverse mix?

**Comment by dconner3** [comment]
If the cap is 120, perhaps we could open it up to first registered-first served for the first 75 or so. Then we could look at the titles/affiliations of the registrants and see if we need to promote the conference more heavily in other areas to balance out the mix?

**Comment by dasaderi** [comment]
@dconner3 I like that idea! @Bubblbu, any progress with registration form draft?

**Comment by dasaderi** [comment]
I emailed PDX Mozilla offices to ask for spaces and sponsorship for Meet and Greet on Friday. I'll let you know the answer as soon as they get back to me.

**Comment by rchampieux** [comment]
@dasaderi you and I need to meet with Madison from OHSU about the CLSB space details.  Can you please ping me with potential opening in your schedule in the next couple of weeks.

**Comment by dasaderi** [comment]
@rchampieux I will be in Montreal next week, but I can meet the week after. Please send me a calendar invite. We are meeting on the 15th for Mozfest prep, so maybe we can do this too the same day?

**Comment by dasaderi** [comment]
Mozilla confirmed the space for the Meet & Greet on Friday February 1. Still waiting to hear about food&drinks sponsorship.

**Comment by dasaderi** [comment]
I just emailed Mozilla requesting funds for Meet and Greet happy hour and for stickers. I'll keep you posted.

**Comment by ashleyfarley** [comment]
Marking as closed
