### ISSUE TITLE
Childcare

### ISSUE THREAD

**Issue by dasaderi** [OpenCon-Cascadia/planning_in_the_open#10]

**Comment by dasaderi** [comment]
@lwinfree please link here or in the gdoc to example childcare interest form you used for Rcascadia. Thanks!

**Comment by dasaderi** [comment]
@rchampieux to follow up with a participant who asked for it and delete that option from registration.

**Comment by rchampieux** [comment]
I deleted the option from the registration.  I'm working with @ashleyfarley on the communication.
