### ISSUE TITLE
Communication

### ISSUE THREAD

**Issue by dasaderi** [OpenCon-Cascadia/planning_in_the_open#11]
- Send out save the date via our channels (opencon mail-list, twitter, ?)
- Figure out a contact email to share on website for people to ask questions and twitter handle/hashtag *#OpenConCascadia18*
- Create a gmail account for email communication ?
- Link email to contact form current on the website 
- Stickers, OCC logo (Ashley) -- Check out standard dimensions: http://hexb.in/sticker.html

**Comment by dasaderi** [comment]
WOW, @ashleyfarley you rock! Thank you!

**Comment by ashleyfarley** [comment]
Ok. I am coming to the conclusion that I am not the best person to work on a logo. I used the free version of Canva, but it's pretty limited. The size should fit the square of the hex sticker dimensions so the rest would be background color and a border. The letter is a little hard to read so need to fix that...

Does anyone else want to take a crack at a logo/sticker? Does this spark any ideas? Thanks!!
<img width="630" alt="occlogo" src="https://user-images.githubusercontent.com/22358242/46631996-f32ab880-cafd-11e8-9ef7-ce072b332f1a.png">

**Comment by dconner3** [comment]
I am going to ask a colleague if she has time to take a crack. What are the dimensions of a typical hex sticker?

**Comment by ashleyfarley** [comment]
Awesome! It is 5.08 cm (2") by 4.39 cm (1.73") here is the link for more details http://hexb.in/sticker.html

**Comment by dconner3** [comment]
I explained the mission statement and vision for OpenCon Cascadia and my colleague has two ideas, but she will need at least a week to put one together. Are able to wait?

**Comment by ashleyfarley** [comment]
I would say of course! That's very kind of her and will totally get credit.

**Comment by dconner3** [comment]
These are "very rough" drafts from Amy Stewart, Reed College Library's Digital Resources Specialist. She wanted to get feedback from the group. She said to ignore "the ugly text (the app I was using doesn’t have a text feature). I would clean it all up in photoshop so any wobbly lines you see would become crisp and geometric."

![hex_stewart01](https://user-images.githubusercontent.com/17661501/46836803-d2659b80-cd67-11e8-8b24-32b011f36c24.jpg)
![hex_stewart02](https://user-images.githubusercontent.com/17661501/46836804-d2659b80-cd67-11e8-87d2-c7a3292bf0b5.jpg)

**Comment by ashleyfarley** [comment]
Awesome! I really like the second one.

**Comment by lwinfree** [comment]
I like the second one too!! Please tell Amy thanks!

**Comment by JEmery972** [comment]
+1 on the second design

On Oct 12, 2018, at 10:23, Lilly Winfree <notifications@github.com> wrote:

I like the second one too!! Please tell Amy thanks!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/OpenCon-Cascadia/planning_in_the_open/issues/11#issuecomment-429399433>,
or mute the thread

**Comment by rchampieux** [comment]
These are awesome!  Please thank her.  I prefer the second one too!

**Comment by dconner3** [comment]
Sounds like there is a growing consensus around option 2. Is there any feedback or suggested changes I should give to the artist?

**Comment by ashleyfarley** [comment]
@dasaderi Do you have a preferred printer for the stickers? If so it might be good to check what the cost/limit is for colors. We might been to simplify the number of colors in the logo - otherwise I do not have any other feedback.

**Comment by dasaderi** [comment]
@dconner3 Thank you so much to you and your friend. I also like the second one, but with a different font for the OpenCon Cascadia, which is what she is suggesting anyway. THANKS again for the work!

As far as places to get the stickers, I used Treehouse stickers before, which is a local sticker company and was happy one time and unhappy the second time. So I might contact them again and ask for a discount for this batch since I complained but never got them to fix the wrong dimension of one of my PREreview stickers batch. :)

**Comment by dconner3** [comment]
Here is a cleaned up version of #2 with a nicer font. What do people think? I like it!

[logo](https://user-images.githubusercontent.com/17661501/47241017-09a6fe80-d39f-11e8-9a12-476b44e4e646.png)

**Comment by ashleyfarley** [comment]
I love it! My only comment would be, if possible, to move the OA logo in the middle up a little bit or fill in the rest of the middle with green (no grey). It looks a little unbalanced (or that's just me). 

I've also started a section in the Appendix of our Google Doc to map out a Communications Plan with suggested content to help everyone strategically and easily share the announcement. Please feel free to add to it!

**Comment by rchampieux** [comment]
I love it too!  I see what you're saying @ashleyfarley and agree.  Thanks for creating the appendix also.

**Comment by dconner3** [comment]
Ok, here is a new version with the Open Access logo moved up a bit based on feedback from @ashleyfarley.

![logo_v2](https://user-images.githubusercontent.com/17661501/47372385-7facad80-d69e-11e8-8f95-0a274eeaca16.png)

**Comment by rchampieux** [comment]
@ashleyfarley @dconner3 I have some access to some grant funds and can get at least a substantial batch of stickers printed asap.

**Comment by ashleyfarley** [comment]
Since I think we are pushing back on making registration live, while we work out the details we can have Nov 2nd - Nov 4th as the go live date for the website/save the date. By then we should have the website updated enough to provide most details (and certainly let me know how I can help).

**Comment by dasaderi** [comment]
@rchampieux @lwinfree I can expense the stickers on Mozilla budget. Do you want me to do this? How many do we want to order? 200?

**Comment by dasaderi** [comment]
Just emailed mozilla to ask for funds for stickers. I'll keep you posted.

**Comment by lwinfree** [comment]
awesome! Yes I would get 200, although you might have to order more than that. I've used sticker robot before & liked them (although they take a while - at least a month)

**Comment by rchampieux** [comment]
Yes, thanks @dasaderi!

**Comment by ashleyfarley** [comment]
A friendly reminders to add to the Outreach List https://docs.google.com/spreadsheets/d/1n1IIeCRD1QqYGLAFingnqjh3hrUEkF-pRqgcEyOhBTw/edit#gid=0 Templated language for communications are located in the Google Drive https://drive.google.com/drive/folders/1KGNKyKUsgL4hSE1Ih4NRybC96j-oekSS
