### ISSUE TITLE
charge for tickets - need input

### ISSUE THREAD

**Issue by lwinfree** [OpenCon-Cascadia/planning_in_the_open#12]
During fundraising meeting, we discussed the idea of charging $10 for tickets. This would serve to:
1) raise $ (for lunch, for example)
2) help with attenuation rates (free events frequently have large #s of people that sign up but don't show up)

Also, $10 should be low enough that most people can afford a ticket. We would also offer free tickets for those that cannot afford $10 (we don't want to turn anyone away for financial reasons!).

According to [OpenCon's site](https://www.opencon2018.org/funding_a_satellite_event), this is within reason: "We have no issue with events charging small amounts for people to attend, however we ask that you aim to only cover costs."

Please comment below with your thoughts/ideas about this proposal!  Thanks!!

**Comment by ashleyfarley** [comment]
I'm not a huge fan of charging a fee, even if nominal - but if it helps serve our mission then I can live with it. :) 

How would this be managed? Paypal? 

I would love to learn more from @dasaderi @daniellecrobinson @rchampieux about the PDX Science Hack day last year? Could that model work for OpenCon? For lunch everyone was responsible for their own food (which I usually prefer as an attendee because it's impossible for a conference to cater to all needs). I also had purchased a tshirt to help support and loved it. But I know that's more work and cost involved...

Maybe a suggested donation? 

I am also not a huge fan of individuals who would need financial assistance having to self declare the need. It's not as equitable as no cost involved.

**Comment by lwinfree** [comment]
Hi! Thanks for your thoughts! Here is a brain dump, and I'd love to chat about this more in the call this afternoon 😄 

I was also on the science hack day planning team, so I can speak a little about that. It was a free event, and we did have a large retention issue where people signed up to come but never showed. For SHD and another conf I helped with (Cascadia R Conf), we had open lunch (where we didn't provide food & people were responsible for bringing or buying their own), and we received negative feedback about that. People were coming back late to the conf too, as they had walked off to go grab lunch. Also, then people have to spend $ for lunch, and it would be about the same as them spending $ on a ticket...unless they bring their own food. That being said, I'm not opposed to cutting out lunch if we had to due to costs, I just don't think it is ideal.

If we charged, I think we would manage payment and registration on Eventbrite or something like it (which is definitely more complicated, but I don't think it is *a lot* more complicated).

+1 to asking for suggested donations! I also like the idea of a shirt, but I don't think we actually made a lot of money off of shirt sales for SHD (I think we maybe got like $200 from them).

In past events where we've done a low-cost ticket & then said 'contact us if you can't afford the ticket', we had several people request free tickets, so I don't think we would lose people/turn people off. Although maybe we did lose people? I suppose there is really no way to tell, but there were definitely people that took us up on the free ticket offer.

**Comment by rchampieux** [comment]
Hi @lwinfree and @ashleyfarley thanks for starting a convo about this.  I agree that we should do t-shirts, thanks for the reminder about that @ashleyfarley.  Now that we have an awesome logo, they'll be easy to design.

Regarding charging - what if we went with a middle ground approach and set the registration up lean-pub style: "choose what you pay" (with the suggestions at $0, $5, and $10 dollars).  I experimented in Eventbrite and you can set up multiple ticket types to accommodate this.

I go back and forth on conference meals.  Something to keep in mind for the CLSB, however, is the lack of food choices in immediate proximity on a Saturday and the closest one is pretty pricy (Elephant's Deli).

**Comment by ashleyfarley** [comment]
@lwinfree Thanks so much for the additional context. I appreciate the brain dump. This is really good experience to build off of. Eventbrite would be great and I agree not a lot more complicated. 

@rchampieux ohhhh that's a really cool idea. 

Looking forward to chatting later today. It seems like this is an area where it's difficult pleasing everyone (re: registration & lunch)

**Comment by rchampieux** [comment]
@ashleyfarley and @lwinfree re lunch - we could also think about asking people to opt in for a conference provided lunch and we can describe close by options for those that prefer to be on their own.  I totally understand this desire - I often use lunch times to be alone 😄

**Comment by dasaderi** [comment]
So was a decision made on this? We need to update that info to the registration form and website before we start disseminating. I'm okay with @rchampieux idea of the "choose what you pay" style.

**Comment by lwinfree** [comment]
Yes we are going with the "choose what you pay" style. I've updated the website, but we still need to update the registration form. Actually, we will need to use like eventbrite now since people will be buying tickets, but we can transfer the info over :)
