### ISSUE TITLE
Save the Date

### ISSUE THREAD

**Issue by rchampieux** [OpenCon-Cascadia/planning_in_the_open#13]
I have drafted email text for the save the date and will add some twitter boilerplate later today.  Please feel free to iterate on any of the drafts.  You can find the drafts and outreach table in here:

https://docs.google.com/document/d/1b4m0oJnQl7vZy-19xnUOoVh2YixGziS5gwefe5oh2DI/edit?usp=sharing.

Please start your outreach/

P.S.  I copied over the communication plan table @ashleyfarley created into this new doc.  I think it might be easier to manage (and confirm when things were sent) via a spreadsheet.  If others agree I'll create that.

**Comment by ashleyfarley** [comment]
Marking this as done!
