### ISSUE TITLE
Open Scholarship panel

### ISSUE THREAD

**Issue by dasaderi** [OpenCon-Cascadia/planning_in_the_open#14]
**Open Scholarship Panel (10:30-10:45am)**  

Panel introducing what open scholarship means to different communities (5 minutes) 
then 5 panelists speaking about: Software, OA publishing space, open educational resources, research, social justice domain → OS as umbrella term + specific talks  
5-7 minutes each  
15-20 questions and discussion  
We need a Moderator - someone who can frame the panel and help the Q and A

Potential speakers:
- Tara Roberts (Mozilla) 
- Steph Wright (Mozilla) - She is already coming to the conference. I'd love if she could talk about how Mozilla is helping open research in the academic space.
- Chrystalee Crain
- David Edwards (OHSU) - he’s new to this but leading a very interesting project to build a culture of open science and operationalize it at OHSU cancer early detection center.  I suggest him because he’s a good speaker, but also in many ways super novice but inspired to help make change.
- Someone who can talk from a funder perspective - Ashley can do this but she is also organizing so if you have other ideas, please add.
- Someone who can talk about Open Education 
- Someone who can talk about community building perspective

Please use this issue to organize the panel. We would love to have names by Wednesday and asks go out asap, deadline Friday Dec 21.

**Comment by ashleyfarley** [comment]
I think Jeff Spies could be a great moderator or maybe talk about Open infrastructure. I believe he is attending, but I can double check if it sounds good to the group.

**Comment by dconner3** [comment]
@ashleyfarley That is a great idea. Yes, please check if he is already planning on attending.

**Comment by dconner3** [comment]
I've created a google doc where we can discuss potential speakers and narrow it down to a final list. I will send it shortly.

**Comment by dasaderi** [comment]
@dconner3, who has been contacted already? Could you please add it to this thread so we can all see it? Thank you. Hope you had a great holiday.

**Comment by dconner3** [comment]
Sorry, I updated the google doc, but not this ticket. I emailed Crystallee Crain, but have not heard back yet. Robin and I are having a call today to talk through next steps for the rest of the panel.

**Comment by rchampieux** [comment]
David Isaak and I met today to finalize a description for the Open Scholarship panel and identify/send the rest of our speaker invites.
 
Panel Description (feel free to comment in doc):
 
The concept of open scholarship can differ between communities of practice. This panel will explore the variations and intersection of ‘openness’ in the domains of science, education, social justice, and big data. Panelists will share their projects, experiences, and perspectives.
 
Panelists (We will records confirmations in Github, we’ve asked to hear from everyone by January 4):
 
Crystalee R Crain: https://www.linkedin.com/in/crystalleecrain/
David Edwards: https://www.linkedin.com/in/davidkedwardsv/
Jen Klaudini:  OER leader in Oregon CC’s. From PCC. From a colleague “She is deeply knowledgeable and a great speaker.  She's doing some cool stuff now leading faculty cohorts in work around OER/open pedagogy and equity. She'd be my first pick.”
Kaela Parks:   PCC OER Steering Committee and advocate for OER from a universal design/accessibility perspective
Douglas Tsoi:  Founder of Portland Underground Graduate School, educator, and socially conscious entrepreneur.
 
Let us   know if you have any questions!

**Comment by rchampieux** [comment]
Hey @ashleyfarley have you confirmed if Jeff Spies is attending?  If so, I agree, let's ask him to moderate.

**Comment by rchampieux** [comment]
David Edwards has confirmed.

**Comment by dasaderi** [comment]
Just a though about this panel. I think we are missing someone who can speak about open software. If one of the invited panelists can't join, I'd consider a name from that sector. Maybe Joe Hand or someone new I don't know?

**Comment by dconner3** [comment]
Crystallee said yes!

**Comment by rchampieux** [comment]
Yes!!!!!!!

**Comment by dasaderi** [comment]
YES! I'll add her to the program. :)

**Comment by rchampieux** [comment]
Hi @dasaderi because we had so many TBC see names in the program, I took that detail out for now.  I would suggest waiting until the end of next week to include individual names.  That way we won't be drawing attending to the holes :-)

**Comment by rchampieux** [comment]
Douglas Tsoi from Portland Underground Graduate School (PUGS) has confirmed.

**Comment by dasaderi** [comment]
Nate asked Hannah Stepanek (core developer at Hypothesis) to speak at this panel. If both Jen and Kaela want to be on the panel, perhaps we can have one of them give a lightening talk instead?

**Comment by rchampieux** [comment]
We asked Jen and Kaela to present together.  It will be great to have Hannah too.  Do we know if she is confirmed?

**Comment by dasaderi** [comment]
Nate confirmed it in the agenda. But I'll email him now. I can't @ him here as he has not yet accepted the invitation to collaborate here I think.

**Comment by xolotl** [comment]
Yes, Hannah Stepanek, Developer at Hypothesis has confirmed she can/will join the panel (she should be registered for the event already. I can add her info (or get her to) if I can find the right place.

**Comment by dasaderi** [comment]
@daniellecrobinson could you please ask Crystalee Crain for a headshot and a short bio for the website? [Here](https://github.com/OpenCon-Cascadia/OpenCon-Cascadia.github.io/issues/45) is Tara's as example.

@xolotl could you do the same for Hannah Stepanek?

@rchampieux will ask David Edward's, Douglas Tsoi's, and Jen Klaudinyi's. 

Once you have them, please either add them directly to [this](https://github.com/OpenCon-Cascadia/OpenCon-Cascadia.github.io/issues/45) issue or add them here and, once we have them all, I'll upload them to the website. 

Thanks!

**Comment by dasaderi** [comment]
Hey all, please send an email to the people you invited to the panel asking them to register. Here's a template https://docs.google.com/document/d/1G2Kw_9edyH_2CSc6LzyOY-HcPpCJMNNWyPMWbDdA-to/edit?usp=sharing. Once you did, please add a thumb up to this comment. Thanks!

**Comment by xolotl** [comment]
@dasaderi My understanding is that Hannah already registered. Is there a way to check?

**Comment by ashleyfarley** [comment]
Yes - I can confirm that Hannah is registered. Thanks!
