### ISSUE TITLE
Catering

### ISSUE THREAD

**Issue by dasaderi** [OpenCon-Cascadia/planning_in_the_open#16]
Friday is taken care of. Daniela is coordinating with Mozilla.

Saturday we need:
- Breakfast (if budget allows). I can get 150 donuts from Coco donuts for ~120.
- Coffee for morning and mid afternoon break + pastries? 
- Lunch - we need data on attendees to ensure we cover dietary restrictions

**Comment by dasaderi** [comment]
Re to Meet&Greet, the schedule is confirmed. I'm coordinating with Mozilla office people about catering, room set up, and security. :)

**Comment by dasaderi** [comment]
Coffee: @lwinfree offered to take care of coffee for breakfast and morning break. 

Donuts: Can anyone take care of ordering donuts? I can do it if Coco Donuts are okay (I live close by), but I know we have opinions about donuts :P. 

Lunch: @lwinfree offered to take care of lunch using Elephants. 
An alternative to Elephant would be using Portland Pedal Power (same catering company as on Friday for M&G). It gives access to many options from several restaurants around the city.  I got an account with them through Mozilla. But happy to use whatever it is easier.

**Comment by dasaderi** [comment]
Catering ToDos:

- [ ] Confirm order with Portland Power Pedal for Friday evening (Daniela)
- [ ] Confirm order of drinks with Katt (Mozilla) for Friday evening (Daniela)
- [X] Decide where to get lunch for Saturday. Daniela can ask a quote with PPP from Cafe Yum.
- [X] Confirm coffee pick up for breakfast and coffee breaks (Lilly)
- [X] Decide if we want donuts and assign someone to pick them up on Saturday AM.

**Comment by rchampieux** [comment]
@lwinfree met about the Saturday catering today.  We nixed the PPP option, as their delivery scheduled seems limited to M-F and the Cafe Yum options were expensive.  Lilly is going to place order with Elephants, they had a good experience for Rconf and it's super convenient.

We are using the Starbucks in the CLSB for coffee and tea breaks.

We set aside $120 for donuts on Saturday AM.  Coco is fine and one of the cheaper options.  @dasaderi are you okay with doing the pick-up?

**Comment by dasaderi** [comment]
Yes, can do Coco! I'll call in to order 120 donuts!

**Comment by rchampieux** [comment]
Great @dasaderi!  Ideally, I'd like to put this on the Library's credit card so we don't have to worry about reimbursements.

**Comment by dasaderi** [comment]
Okay, thanks! So, do you want to call Coco donuts on Milwaukie and pay on the phone? I can still make the reservation and certainly will do pick up. Let me know what's easiest for you.

**Comment by rchampieux** [comment]
Yes, that would be ideal.  Should I place the order then?  If so, what time do you want to pick up?

**Comment by dasaderi** [comment]
Yes, please. Make the order @rchampieux. I'll pick up at 7:45am on Saturday Feb 2. You can leave my phone number as contact. Thanks!

**Comment by LuciMoore** [comment]
by the way, I need a copy of the lunch receipt to submit to All Hill for reimbursement!
