### ISSUE TITLE
Communications/Marketing 

### ISSUE THREAD

**Issue by ashleyfarley** [OpenCon-Cascadia/planning_in_the_open#17]
I was wondering if it would be worthwhile to be listed as an OpenCon Satellite Event? Or has this discussion happened already? https://www.opencon2018.org/satellite-2015-old

**Comment by dasaderi** [comment]
Good point @ashleyfarley, we never filled in the form. I'll email Joe and ask.

**Comment by dasaderi** [comment]
I created two flyers to advertise OpenCon Cascadia using the templates that OpenCon made available. More resources here https://www.opencon2018.org/satellite_resources. 
The editable flyers are in the communication folder in our drive. Here are the png:

![opencon cascadia posters](https://user-images.githubusercontent.com/13750121/50164508-c5998280-0297-11e9-9e5e-3c6254e938ab.png)

**Comment by ashleyfarley** [comment]
Fantastic poster! Thanks so much for creating it.

**Comment by dasaderi** [comment]
Joe said to fill [this](http://righttoresearch.nationbuilder.com/users/event_pages/new?parent_id=70) and we will be added to the list. I tried three times, but it keeps spinning and doesn't save. Anyone else want to try? For the text, I copied and pasted the text from the [eventbrite](https://www.eventbrite.com/e/opencon-cascadia-tickets-52732189398).

**Comment by ashleyfarley** [comment]
I can give it a try!

**Comment by ashleyfarley** [comment]
It's been submitted. The form was very fussy.

**Comment by rchampieux** [comment]
Hi!  Here is a new/alternative version for the flyer.  I can make changes and folks should feel free to adopt this for their own use.
[OCC-Flyer-New.pdf](https://github.com/OpenCon-Cascadia/planning_in_the_open/files/2728800/OCC-Flyer-New.pdf)

**Comment by dasaderi** [comment]
150 stickers ordered!

**Comment by dasaderi** [comment]
Stickers have arrived. You can tweet about it or RT my Tweet if you want to use it as an excuse to advertize https://twitter.com/Neurosarda/status/1083099851536031744. 

:)

**Comment by dasaderi** [comment]
@rchampieux @PJP1313 can we list here what OHSU outreach we have already done in January? I'd like to hit again GSO, BEHN, NGP, but have no idea how to reach School of Public Health, nursing, or other OHSU relevant mail lists. 

- [ ] GSO (Daniela)
- [x] BEHN (Daniela)
- [x] NGP (Daniela)
- [X] OHSU Library (Pam and Robin)
- [X] BioData Club and Data Jamboree (Robin)
- [x] School of Public Health (Robin)
- [X] Research News

**Comment by rchampieux** [comment]
Hi,

I sent an invite to all OHSU Library staff a couple weeks back, and either @PJP1313  or I can do another one this week.  I think our new Director, Kris Alpi is going to do a lightening talk on Friday, so I'm waiting to confirm that before we push out again.

I also confirmed with the OHSU Research News people that I can post something on their blog this week.

I will send another round of outreach to BioData Club, the School of Public Health, OCTRI, and CEDAR this week.

**Comment by rchampieux** [comment]
Additionally - per last week's meeting we are supposed to be reaching out to Community Colleges.  Here is the list:

@rchampieux  - PCC
@walecain - Lane Community College
Jill Emery - Mt. Hood (I think)

**Comment by dasaderi** [comment]
Sorry, reopened because I'm not done with these tasks. Thanks Robin for the clarification on OHSU outreach efforts. :)
