### ISSUE TITLE
Post Do-a-thon info to site (as new page)

### ISSUE THREAD

**Issue by rchampieux** [OpenCon-Cascadia/planning_in_the_open#19]
@Bubblbu and @lwinfree 
- The text describing the OpenCon Cascadia do-a-thon text is ready to go.  You can find it at the bottom of [this doc](https://docs.google.com/document/d/1NeExpRFfk4iV8DhuNqOEW4trjfd4ENXtjYl0wqtT0kc/edit)

- The [proposal submission form](https://goo.gl/forms/bEDVkneOtGDvEgUD3) is also ready and linked to from the doc.  

We need to publish the do-a-thon description to the website as a new page.  Can one of you do this tomorrow?  Please feel free to make edits to the description or form!

**Comment by rchampieux** [comment]
Once info is published to site:
- [ ] Draft do-a-thon focused social media and email promotion.
- [ ] Ask organizers to and friends to submit proposals, so we have things folks can engage with ahead of time.
- [ ] Figure out where we want to post projects.  Should we use github (it can be a huge barrier), Gdocs, the website, other?

**Comment by dasaderi** [comment]
Amazing work you all! Thank you!

**Comment by lwinfree** [comment]
Thanks Robin! I can work on this over the weekend

**Comment by rchampieux** [comment]
Hi @lwinfree - I'm going to try to do this today, because we want to get some communication out before Friday.  Thanks for all your help.

**Comment by rchampieux** [comment]
HI @Bubblbu AND @lwinfree I got the page up so no need to worry about this.

**Comment by lwinfree** [comment]
@rchampieux you are an amazing rockstar!!
