### ISSUE TITLE
Do-a-Thon

### ISSUE THREAD

**Issue by rchampieux** [OpenCon-Cascadia/planning_in_the_open#20]
Some more immediate to dos now that do-a-thon page is up.
- [ ] Draft do-a-thon focused social media and email promotion.
- [ ] Ask organizers to and friends to submit proposals, so we have things folks can engage with ahead of time.
- [ ] Figure out where we want to post projects.  Should we use github (it can be a huge barrier), Gdocs, the website, other?

**Comment by dasaderi** [comment]
@xolotl, above are some to-dos listed by @rchampieux. Maybe something you can help with here?

**Comment by xolotl** [comment]
@rchampieux I started out by looking at the do-a-thon webpage and made a small suggested change to the page (2 links > 1 button) which @dasaderi merged.

I submitted a do-a-thon idea to try it out myself, so there should be a new one.

I would suggest either GitHub (as one might want the projects to live going forward on the website, which is in GitHub too), tho I agree it can be a barrier, or gdocs, as most folks either already know how to use them or find them easy enough to learn. If we use gdocs, I'd be happy to transfer appropriate materials to the website later for ongoing recordkeeping.

I've started a draft of do-a-thon communications in [this gdoc](https://docs.google.com/document/d/1DWAsGEd_SeM9i529hIXWrmJ1NjrxQDWt1fR2IVEvLbE/edit?usp=sharing) and will move it forward as well as welcoming contributions from others.

**Comment by xolotl** [comment]
@rchampieux @dasaderi et al: just to make sure, the do-a-thon is focusing on "activities that seek to make research and scholarship more open, inclusive, and accessible" as per the webpage? Just wanted to check as that seems like a subset of the overall event focus.

**Comment by rchampieux** [comment]
That's good feedback @xolotl.  I used that phrase to try to capture everything, but i can see how that seems limited.  I need to pack up for home, but please feel free to suggest alternative language 😸

**Comment by xolotl** [comment]
@rchampieux ok, I just wasn't sure if we were trying to focus the do-a-thon on "research and scholarship"...I'll propose wider language.

**Comment by dasaderi** [comment]
Nate, I just asked Lilly or Asura to add you as collaborator on website repo so you can make direct changes. Thanks! :)

**Comment by dasaderi** [comment]
@Bubblbu will link projects that have been submitted on the back end on GitHub and they will show up on website.

@xolotl will revise language on form and website to make it more general.

**Comment by xolotl** [comment]
I created a [pull request](https://github.com/OpenCon-Cascadia/OpenCon-Cascadia.github.io/pull/54) with suggested changes to the language on the do-a-thon page so everyone could review/comment/suggest changes before we accept it.

I don't think I have rights to change the similar language on the form, so if someone could give nate@xolotl.org editing rights there, I could also make changes there based on whatever final language we adopt.

**Comment by xolotl** [comment]
OK, @dasaderi merged the PR to the website and I copied the same language to the google form, so revising the language to make it more genreal is done unless someone wants to make changes.

**Comment by rchampieux** [comment]
Hi @xolotl you should have editable access to the form - it's in the OpenCon Cascadia > Program > Do-a-Thon folder.  Also, was there a decision on Friday's call about how we'll post the submitted projects in advance?
