### ISSUE TITLE
Nametags & Co.

### ISSUE THREAD

**Issue by dasaderi** [OpenCon-Cascadia/planning_in_the_open#21]
- [x] Nametags
- [ ] Pronouns stickers
- [x] Pens and sharpies
- [x] Different color stickers for mentors and mentees 
- [x] Big sticky post-it for do-a-thons and conference +/- ? 
- [x] Little pencils for M&G bingo (Pam said would procure from the library)
- [x] Print a few copies of our CoC
- [x] Stickers to indicate no picture.

**Comment by rchampieux** [comment]
I don't think we should print programs.
