### ISSUE TITLE
Data Viz of Attendee Demographics

### ISSUE THREAD

**Issue by rchampieux** [OpenCon-Cascadia/planning_in_the_open#24]
It might be nice to be able to show some info regarding attendee demographics, like geographically where people are coming from, roles, expertise, institutional affiliation, etc.  Is anyone interested in or up for experimenting with this?  @walecain and @Bubblbu I'm thinking of you 👋 🌈 💯

**Comment by Bubblbu** [comment]
Sure! Can you share the list of attendees (and maybe speakers) with me with the information?

We would probably need to compile the speaker information right?

I can look into creating a few plots and stats for blog posts, the web page, for slides, etc.

**Comment by rchampieux** [comment]
Just sent you an email follow up 😸

**Comment by Bubblbu** [comment]
I added a folder to our Google Drive with the current state of registrations + a python notebook + a few initial plots

happy to make changes to layout/colourmap or create different graphs if needed :)
