### ISSUE TITLE
Final Communication with our Speakers

### ISSUE THREAD

**Issue by rchampieux** [OpenCon-Cascadia/planning_in_the_open#25]
Start listing things we should communicate/confirm before the 1st.  Brainstorming here:

- Should it be sent by panel moderators?
- Include reminder about time of panel, request for slides in advance (but not necessary), goals and maybe one high level question moderator hopes to ask, any name pronunciation questions, thank you, link to directions and parking info, reminder about hashtag.

**Comment by LuciMoore** [comment]
@rchampieux I think it should be sent by the moderators. Sanjay just DMed on Twitter to confirm these details

**Comment by LuciMoore** [comment]
also, should we come up with a list of questions to ask in case the audience doesn't have questions? or maybe that won't be a problem

**Comment by rchampieux** [comment]
Yes, I think so @LuciMoore.  For each panel, I think it would be good to have one question prepped for the moderator to kick the Q&A off and then at least 2 more in case things slown down.  We should also have some strategies in place to ensure that some folks don't accidentally or intentionally use their privilege to take up space/time.

**Comment by dasaderi** [comment]
- Daniela will send email to lightening talk speakers (stick to 3-5 minutes, no more than 3 slides; provide order)
- @LuciMoore will send email to DEI panelists (Confirm the time and location for their panel; format;
send over slides (5 top); if you want you can send them a question you plan to ask them.
- Nick (@rchampieux will ask him) will email OS panelists asking for similar things.

**Comment by dasaderi** [comment]
Emails to all lightening talk speakers sent. 
@rchampieux are you reaching out to Nick asking him to email the panelists?

**Comment by rchampieux** [comment]
Yes, I'll do this tomorrow.

**Comment by rchampieux** [comment]
Hi all - just confirming that I sent the email to our OS panelists.  Rather then trying to coordinate with Nick and have him send it (he's at a conference).  I just used the opportunity to introduce him.  Thanks @LuciMoore for creating the template, I just updated that for my purposes.  I also created a slide deck for the OS panel.

**Comment by LuciMoore** [comment]
I also e-mailed the DEI panel
