### ISSUE TITLE
Final Communication with Our Attendees

### ISSUE THREAD

**Issue by rchampieux** [OpenCon-Cascadia/planning_in_the_open#26]
Start making list of things to communicate and remind:

- Code of Conduct
- Directions and parking
- How to get in touch with us, if they run into any issues
- Do-a-Thon

Please add to and refine.

**Comment by dasaderi** [comment]
@ashleyfarley will send an email on Monday. [Here](https://www.ohsu.edu/xd/about/visiting/directions/clsb-life-sciences.cfm) is info about OHSU and parking.  For Mozilla, no parking there. Take public transport or park on paying parking lots. Eventbrite will send reminder 48hrs before. 

@rchampieux, question about space at OHSU. Is everything set up for that? We need to add room number to program and email to participants. Do we have only one big room or also some small rooms for do-a-thons?

**Comment by rchampieux** [comment]
Yes, everything is set up for space at OHSU.  We have both learning studios - they have a capacity of 180 each.  The divider will be up, so we can use both for do-a-thons.  We don't have small rooms.

**Comment by rchampieux** [comment]
I will confirm the room number tomorrow - I have an email out to our contact in OHSU facilities.  Unfortunately, I can't access the info off our network.

**Comment by xolotl** [comment]
@rchampieux: As you are checking on the rooms...

Are the rooms set up with round tables or is it theater style or other? I'm assuming we can have each do-a-thon activity take over a portion of each room, but some layouts may be better than others.

Also, wondering what tools will be available for each do-a-thon activity. Assuming wifi and power, but would any group also be able to project? Or maybe whiteboards of paper easel charts? We might want to communicate what's available so do-a-thoners can plan accordingly.

**Comment by rchampieux** [comment]
Tables (square, not round ), which can be moved around. Wifi and power, yes.  The only projector is at the podium, but there are 6 screens in the room and we can select to project to a single screen.  I am buying paper sticky charts and markers (among other things)  I agree about communicating with folks about this.  I can do this, but probably not until Tuesday.  If there's anything you want me to get, please let me know.

**Comment by rchampieux** [comment]
When I'm back in the office on Tuesday, I can take a pick...so you all have a sense of it.  I've caught an awful cold and I'm trying to take tomorrow off to get better, but I will be checking in.

**Comment by xolotl** [comment]
It sounds like a flexible setup for a variety of situations, which sounds like what's needed!

**Comment by rchampieux** [comment]
Yes, it's a really modular space 💯
