### ISSUE TITLE
Unconference(s) / Do-a-thon(s) / Workshop(s)

### ISSUE THREAD

**Issue by dasaderi** [OpenCon-Cascadia/planning_in_the_open#4]
* Collaboration best practices in community building and tools/techniques.

* Open practice strategies and methodologies, including governance, outreach, community building, peer-review.

* Mix of unconference, short training sessions, casual networking in the evenings, short workshops, intro workshops for people new to open science.

* Use mentoring to link people and technology to keep them connected after the event. 

* Design thinking strategies that can empower work at the conference and beyond.

**Comment by dasaderi** [comment]
I changed the title of this issue to reflect the schedule name. 

From the notes of the last call, here are some suggestions for unconferences/do-a-thons/workshops. Please add and vote!   
Start time 3:45-4:45pm, Saturday Feb 2. 

- Frictionless data (Lilly; works well as a workshop/hands-on session)
- Advocacy unconference (discussion based on book Blueprint for revolution)
- Funding work at the intersection between scholarship and social justice - open facilitated discussion
- Mentorship - empowering early-career professionals to take action and make the change they want to see
- Story circles
- [Reproducibility workshop](https://community.plantae.org/article/5024904911976924657/material-for-our-plantbio18-quot-reproducibility-for-everyone-quot-workshop) designed by group of eLIFE Ambassadors (Daniela)
- Design thinking strategy to approach problems and community building efforts (OpenCon has lots o resources that we can use) (Daniela)
- Failure story circle (#okfail) (Danielle)
- Fundraising for open projects toolkit (Daniela has materials on this)

**Comment by ashleyfarley** [comment]
The OpenCon Cascadia email box received this message: 
"While I received an invitation to register for the conference, I haven't seen a call for program proposals.  If that hasn't happened yet, could you please forward along instructions for submitting program ideas for consideration?many thanks,~ DC"
--
I honestly hadn't thought about proposals. How should I respond? Thanks!

**Comment by lwinfree** [comment]
thanks @ashleyfarley! Would you respond & say that we aren't doing a broad call for proposals because we have very targeted keynotes and panels...? Although this person (whose name I edited out of your comment for privacy :-) ) might be good to contact for a panel

**Comment by dconner3** [comment]
@ashleyfarley, this person is one of our sponsors and mentioned that they wanted to speak. So when you write back, you could mention the Friday night speaking spots as an opportunity for them to talk about their project. You can follow up with me over email if you have questions about this.

**Comment by ashleyfarley** [comment]
Great! Thank you very much for the additional context. @lwinfree thank you for the privacy check - I will be more aware in the future.
