### ISSUE TITLE
Fundraising

### ISSUE THREAD

**Issue by dasaderi** [OpenCon-Cascadia/planning_in_the_open#6]
We would like the conference to be free of charge to participants. The Location team will try to confirm the venue in the next two weeks (by July 13), and hopefully that will give us a better idea about how much and what to fundraise for.

**Comment by rchampieux** [comment]
@lwinfree and I are meeting on 10/22 to kick off the fundraising campaign.

**Comment by rchampieux** [comment]
@dasaderi Lilly and I are working on the budget and fundraising - has Mozilla confirmed about sponsoring Friday night drinks and food?

**Comment by JEmery972** [comment]
I think the $1,500 per institution ask is reasonable. I initially asked for PSU to sponsor at $1,000 but think $1,500 is not unreasonable. If we get language in place for the ask I can make it next week at our leadership meeting.

**Comment by rchampieux** [comment]
Thanks @JEmery972 - what day is your leadership meeting?

**Comment by JEmery972** [comment]
Next Tuesday afternoon starting at 2 PM

As for talking points that will resonate:

collaborative effort  with the research community at large
 
inclusive nature of the event 

framework for developing of open practices

**Comment by dconner3** [comment]
I'm not sure what my institutions response will be, but I am comfortable asking if they will support at the $1,500 level. I will wait to see how the call went today to see if anything changed before approaching my decision makers next week.

**Comment by dasaderi** [comment]
I'm happy to announce that I will have the funds for the Meet and Greet and the stickers from Mozilla. YAY!

**Comment by ashleyfarley** [comment]
Yay!!! You are a rockstar. Thanks so much!
