### ISSUE TITLE
Mission Statement

### ISSUE THREAD

**Issue by dasaderi** [OpenCon-Cascadia/planning_in_the_open#7]
We need to write our Mission Statement and share it on the website.

At our last call (August 10) we identified some key points we want coming across in our Mission Statement. Possibly use text in this repo's README.md as starting point.

From call's brainstorming session:

- We want the mission statement to speak to different communities operating in the space, communicating our message across disciplinary boundaries on the social, political, and technical challenged we share in open work. 
- We want to develop intersections between academia and research communities 
- We want to support and foster communication flows between groups
- We want to empower the community to work for open projects. Connect with those who might not be able to travel further. 
- We want OpenCon Cascadia to be a community-driven, collaborative event to allow for organic partnerships to form on the topic of open. A focus on fostering mentorships, safely discuss current issues in the ecosystem, while problem solving for potential solutions. While the event occurs over two days the effects will hopefully have a lasting impact until the next OpenCascadia. 
- We want it to be a forum for coordinating existing open projects in the PWN across different disciplines and spaces (libraries, research departments, policy, …?). We want to engage young professionals and empower them to make change.
- Openness as DEI/Social Justice issue; open research as more collaborative / reproducible 
- Emphasise the local character (e.g., contrast to OpenCon as the global venue/community, FORCE11, ...) but this one specifically to connect and work with other people in the area
- OpenCon Cascadia as a place that flattens the hierarchy of research, providing a more open and equitable place for researchers and research users, of all descriptions.
- Emphasis on building a community where to connect individuals and organizations from different domain areas.

**Comment by ashleyfarley** [comment]
1st Draft - feel free to iterate 

It is the mission of OpenCon Cascadia to build an inclusive, collaborative community, spanning all disciplines and research communities, by flattening hierarchical structures to provide a more open and equitable place for individuals to thrive. This Pacific Northwest community aims to support and foster, mentorship, innovative solutions, and energizing conversations on all things open, with a focus on building up young or new professionals. 


**Maybe the following can be part of a Code of Conduct to provide more details on DEI:**
Regardless of race, ethnicity, gender, nationality, religious and political views, and other aspects of their identities, individuals are included based on their enormous potential to contribute to the community. It is imperative that all participants—and, indeed, all members of our OpenCon Cascadia community—are valued, respected, and provided with equal opportunities to thrive.

**Comment by dconner3** [comment]
This first draft looks really great! I just added in a few phrases to this 2nd version:

It is the mission of OpenCon Cascadia to build an inclusive, collaborative community, spanning all disciplines, domains, and research communities, by flattening hierarchical structures to provide a more open and equitable place for individuals to thrive. This Pacific Northwest community aims to support and foster mentorship, innovative solutions, collective projects, and energizing conversations on all things open, with a focus on building up young or new professionals. 

Also, I like the idea of including more details on DEI in a code of conduct. Should we start a separate GitHub Issue for the Code of Conduct?

**Comment by dasaderi** [comment]
Great! Please create a CoC issue. :)

**Comment by dconner3** [comment]
Done: https://github.com/OpenCon-Cascadia/planning_in_the_open/issues/8

**Comment by ashleyfarley** [comment]
Great! Do we need to get sign off from the larger group on the mission
statement before adding to the website?

**Comment by ashleyfarley** [comment]
This has been added to the website. Marking as closed
