### ISSUE TITLE
Registration form

### ISSUE THREAD

**Issue by Bubblbu** [OpenCon-Cascadia/planning_in_the_open#9]
Editable link for the Google Form is in the organisation document. (tbd)

Currently suggested fields for the registration form:

- Disclaimers
  - Free event
  - Email
  - Privacy
- Personal
  - Full Name
  - Age range
  - Email
  - Institution
  - Current job/career status
  - Pronouns
  - Mentorship section (related to #5)
  - Have you attended an OpenCon event before? 
- Attendance
  - Planning to attend day 1, day 2, or both?
  - Dietary restrictions
  - Disability accommodations
- Childcare questions
  - how many children
  - what ages
  - morning/afternoon/all day
- Other things
  - Language around the option of sponsorship (yes/no)
  - Email Update, opt in
  - Acceptance of Code of Conduct (#8)

**Comment by Bubblbu** [comment]
added link to the Google form to the "important links" section of the organising document

**Comment by dasaderi** [comment]
@Bubblbu I added a few things directly to the form. But it still needs work. I'll find some time to work on it this weekend. @ashleyfarley and @rchampieux do you have time to help out with this? 
Thank you all!

**Comment by ashleyfarley** [comment]
I will have some time later today and can work on it!

**Comment by rchampieux** [comment]
Yes, I can work on it a bit too.  Question - should we just edit in them form or do you want us to discuss suggestions first.

**Comment by rchampieux** [comment]
Also - another questions.  Childcare questions are too understand potential need, correct?  Maybe we should state that we are still investigating, but are gauging interest?

**Comment by ashleyfarley** [comment]
I vote for just making changes unless it's something warranting discussion. 
I've taken a stab at it and here are a few questions:

- Do we need to include the opening reception in the form? 
-"What kind of mentorship would you prefer?" The answers to this seem to signify the desired structure of the conference. So I've created a question geared toward conference structure and reworded the responses for mentorship. Please feel free to edit/restructure 
-Do we need a note that their registration is appending approval/confirmation of their registration will be sent to them?

**Comment by dasaderi** [comment]
@rchampieux, yes, I think it's good to frame it that way.
@ashleyfarley I'm not sure I understand your question fully. What do you mean by "opening reception"? 

Thanks for editing the mentorship portion. I have not yet looked at that. Perhaps worth getting the "mentorship" team on a call to make sure we think this through together?

I'm not sure about registration approval. On one hand that would be more work for us, on the other hand it would allow for a closer monitoring of participants and ensure a diverse attendance. Maybe we can do as it was suggested, that we do first come first served for the first 75 and then curate the rest?

**Comment by ashleyfarley** [comment]
Apologies - I meant the Friday meet and greet.

Do we have a start and end time for each day? This should probably be
advertised on registration.

Agreed we should discuss the mentorship portion a bit more.

That approach works for me. At 75+ we would somehow need to make it clear
that filling out the registration form does not guarantee a spot. And there
might be a need for a waitlist at some point (I’m assuming this will be a
popular event :) )

**Comment by dasaderi** [comment]
Good point, Ashley. We don't have a time yet. But I told Mozilla that we'd like the office starting at 5pm. So maybe the Meet & Greet can be 6-8pm?

**Comment by ashleyfarley** [comment]
I think that makes sense. What about times for Day 1 and Day 2? Thanks!

**Comment by ashleyfarley** [comment]
The mentorship group had a call today and finalized our goal for the form. For ease of use we just have a question in the beginning and removed the mentorship section. I think overall it's looking very complete. Let me know if I can help with any outstanding pieces.

**Comment by dasaderi** [comment]
Thank you so much for the update @ashleyfarley. I think the registration from is almost ready. I was going to add text around the fact that only the first 75 registered will get a secured spot, but didn't know how to phrase that. Also, since we say that the organizing committee will have access to their private information, I think it's fair to list the committee members. We can link to the page on the website where we put our names as organizing committee. Thoughts?

**Comment by dasaderi** [comment]
The Wikipedia image of mt hood with reflection is free to use and beautiful (also looks like our logo). So I added it to the header of the registration form. @lwinfree and @Bubblbu maybe it can be also the background of the website? I saved the image in our shared website text folder. :)

https://en.wikipedia.org/wiki/Mount_Hood

**Comment by ashleyfarley** [comment]
Maybe the language should be something like "[...]For this reason, submission of the registration form is not a confirmation for attendance" And then we send a confirmation email to each person? I just wonder if we need to do any sort of vetting - with having the registration form widely shared online and it's free. Although I've never organized such an event so maybe it isn't an issue? 

I think posting the organizing committee info on the website and linking to it is a great idea. Do we need a short bio/pic? Or keep it simple with name/Twitter handle? 

The pictures looks great for the header of the registration form!

**Comment by dasaderi** [comment]
Thank you @ashleyfarley for writing the language for the registration form. I'll add it in later (or feel free to do it yourself if you have time). I don't know about the vetting part. @rchampieux ideas?

I think a pic and short bio would be nice, but it might take some time to collect that info. I'm okay either way. When are we shooting to have this done?

**Comment by ashleyfarley** [comment]
For timeline I think we should aim to finalize before the end of OpenCon -
November 4th - so that we can advertise then. The OpenCon community will be
really engaged then. But I'm also happy to take the time needed to get it
right.

**Comment by rchampieux** [comment]
Hi @ashleyfarley @dasaderi and @Bubblbu Lilly and I are taking another pass through the reg form.  Some major and minor comments:

1).  By this Friday, we should have a save the date read and tweeted out.
2). Agree with @ashleyfarley that Nov. 4 is a good deadline for opening registration.
3).  We'd like to take a stab at making the introductory text in the registration form a bit more concise.  It's sounds like you're all okay if we just start hacking on the form 😄 
4).  Please see our issue about a small conference / registration fee (#12).  We checked the OpenCon satellite event info and it is allowable.  In @lwinfree 's experience with R conf, it was a helpful tool for actually getting people there who registered.

**Comment by ashleyfarley** [comment]
Registration is now live! Marking this as closed.
